### ISSUE TITLE
Patch for joining private channels 

### ISSUE THREAD

**Issue by relip** [nTraum/gitlab-irc#2]
Just pushed to my (forked) repo, I'm just wondering is it okay to PR this commit. 

https://github.com/relip/gitlab-irc/commit/0d5c797ec4b70dbc7e568ab25d98c43a69f67c7e

**Comment by nTraum** [comment]
Password protected channels should be supported of course, thanks for the patch. :+1: 

Can we get rid of the `if` by using the following snippet?

``` ruby
c.channels = [$config['irc']['channel'], $config['irc']['channel_password'].compact.join(' ')
```

It would join both `Strings` when a password is set, but does not leave a trailing whitespace when the password is missing.

Don't have time to test it on my own right now, sorry. :x

**Comment by nTraum** [comment]
We'd also need to modify the default config file so people know how to specify the channel password.

**Comment by relip** [comment]
Okay, committed and PR'ed.

**Comment by nTraum** [comment]
Done.
